
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: feature_flag_engine_development

  
test:
  <<: *default
  database: feature_flag_enginse_test

production:
  primary: &primary_production
    <<: *default
    database: feature_flag_engine_production
    username: feature_flag_engine
    password: <%= ENV["FEATURE_FLAG_ENGINE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: feature_flag_engine_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: feature_flag_engine_production_queue
    migrations_paths: db/queue_migrate
